// <auto-generated />
using System;
using AgnusCrm.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AgnusCrm.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20190323201954_add-product-property")]
    partial class addproductproperty
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.0-rtm-35687")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AgnusCrm.Models.Brand", b =>
                {
                    b.Property<string>("code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.HasKey("code");

                    b.ToTable("Brand");
                });

            modelBuilder.Entity("AgnusCrm.Models.Coin", b =>
                {
                    b.Property<string>("code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(3);

                    b.Property<string>("Symbol")
                        .HasMaxLength(5);

                    b.Property<int>("decimalPlaces");

                    b.Property<string>("desc")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("logo");

                    b.HasKey("code");

                    b.ToTable("Coin");

                    b.HasData(
                        new
                        {
                            code = "MZN",
                            Symbol = "MT",
                            decimalPlaces = 2,
                            desc = "Metical"
                        },
                        new
                        {
                            code = "USD",
                            Symbol = "$",
                            decimalPlaces = 0,
                            desc = "Dollar"
                        },
                        new
                        {
                            code = "ZAR",
                            Symbol = "Rand",
                            decimalPlaces = 0,
                            desc = "Rand's"
                        },
                        new
                        {
                            code = "EUR",
                            Symbol = "EUR",
                            decimalPlaces = 0,
                            desc = "Euro"
                        });
                });

            modelBuilder.Entity("AgnusCrm.Models.Contact", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Status");

                    b.Property<string>("cellPhone")
                        .HasMaxLength(20);

                    b.Property<string>("code")
                        .HasMaxLength(20);

                    b.Property<string>("email");

                    b.Property<string>("emailAlt")
                        .HasMaxLength(50);

                    b.Property<string>("firstName")
                        .HasMaxLength(50);

                    b.Property<string>("fullName")
                        .HasMaxLength(100);

                    b.Property<string>("lastName")
                        .HasMaxLength(50);

                    b.Property<string>("middleName")
                        .HasMaxLength(50);

                    b.Property<string>("telephone")
                        .HasMaxLength(20);

                    b.Property<string>("title")
                        .HasMaxLength(10);

                    b.Property<string>("type")
                        .HasMaxLength(20);

                    b.Property<string>("userId");

                    b.HasKey("id");

                    b.ToTable("Contact");
                });

            modelBuilder.Entity("AgnusCrm.Models.Contact_Entity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("contactId");

                    b.Property<int>("entityId");

                    b.Property<string>("name")
                        .HasMaxLength(20);

                    b.Property<string>("type")
                        .HasMaxLength(20);

                    b.Property<string>("value")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.HasIndex("contactId");

                    b.HasIndex("entityId");

                    b.ToTable("Contact_Entity");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.AccountExecutive", b =>
                {
                    b.Property<string>("accountExecutiveId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("accountExecutiveName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("email")
                        .HasMaxLength(50);

                    b.Property<string>("phone")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.Property<string>("systemUserId")
                        .HasMaxLength(38);

                    b.HasKey("accountExecutiveId");

                    b.ToTable("AccountExecutive");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.Activity", b =>
                {
                    b.Property<string>("activityId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("activityName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("colorHex")
                        .HasMaxLength(10);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.HasKey("activityId");

                    b.ToTable("Activity");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.Channel", b =>
                {
                    b.Property<string>("channelId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("channelName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("colorHex")
                        .HasMaxLength(10);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.HasKey("channelId");

                    b.ToTable("Channel");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.Lead", b =>
                {
                    b.Property<string>("leadId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("accountExecutiveId")
                        .HasMaxLength(38);

                    b.Property<string>("channelId")
                        .HasMaxLength(38);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .HasMaxLength(38);

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<bool>("isConverted");

                    b.Property<bool>("isQualified");

                    b.Property<string>("leadName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.HasKey("leadId");

                    b.HasIndex("accountExecutiveId");

                    b.HasIndex("channelId");

                    b.ToTable("Lead");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.LeadLine", b =>
                {
                    b.Property<string>("leadLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("activityId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("endDate");

                    b.Property<string>("leadId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("startDate");

                    b.HasKey("leadLineId");

                    b.HasIndex("activityId");

                    b.HasIndex("leadId");

                    b.ToTable("LeadLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.Opportunity", b =>
                {
                    b.Property<string>("opportunityId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("accountExecutiveId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .HasMaxLength(38);

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<DateTime>("estimatedClosingDate");

                    b.Property<decimal>("estimatedRevenue");

                    b.Property<string>("opportunityName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("probability");

                    b.Property<string>("ratingId")
                        .HasMaxLength(38);

                    b.Property<string>("stageId")
                        .HasMaxLength(38);

                    b.HasKey("opportunityId");

                    b.HasIndex("accountExecutiveId");

                    b.HasIndex("customerId");

                    b.HasIndex("ratingId");

                    b.HasIndex("stageId");

                    b.ToTable("Opportunity");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.OpportunityLine", b =>
                {
                    b.Property<string>("opportunityLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("activityId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(200);

                    b.Property<DateTime>("endDate");

                    b.Property<string>("opportunityId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("startDate");

                    b.HasKey("opportunityLineId");

                    b.HasIndex("activityId");

                    b.HasIndex("opportunityId");

                    b.ToTable("OpportunityLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.Rating", b =>
                {
                    b.Property<string>("ratingId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("colorHex")
                        .HasMaxLength(10);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("ratingName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("ratingId");

                    b.ToTable("Rating");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.Stage", b =>
                {
                    b.Property<string>("stageId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("colorHex")
                        .HasMaxLength(10);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("stageName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("stageId");

                    b.ToTable("Stage");
                });

            modelBuilder.Entity("AgnusCrm.Models.Entity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("address")
                        .HasMaxLength(100);

                    b.Property<string>("code")
                        .HasMaxLength(20);

                    b.Property<string>("coin")
                        .HasMaxLength(3);

                    b.Property<string>("contributing_Number")
                        .HasMaxLength(20);

                    b.Property<string>("country")
                        .HasMaxLength(20);

                    b.Property<string>("locality")
                        .HasMaxLength(20);

                    b.Property<string>("name")
                        .HasMaxLength(50);

                    b.Property<string>("telphone")
                        .HasMaxLength(30);

                    b.Property<string>("type")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.HasIndex("coin");

                    b.ToTable("Entity");
                });

            modelBuilder.Entity("AgnusCrm.Models.Family", b =>
                {
                    b.Property<string>("code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20);

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.HasKey("code");

                    b.ToTable("Family");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Branch", b =>
                {
                    b.Property<string>("branchId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<bool>("isDefaultBranch");

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.HasKey("branchId");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Customer", b =>
                {
                    b.Property<string>("customerId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<int>("pvp");

                    b.Property<int>("size");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.HasKey("customerId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.CustomerLine", b =>
                {
                    b.Property<string>("customerLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .HasMaxLength(38);

                    b.Property<string>("fax")
                        .HasMaxLength(20);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("gender");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("middleName")
                        .HasMaxLength(20);

                    b.Property<string>("mobilePhone")
                        .HasMaxLength(20);

                    b.Property<string>("nickName")
                        .HasMaxLength(20);

                    b.Property<string>("officePhone")
                        .HasMaxLength(20);

                    b.Property<string>("personalEmail")
                        .HasMaxLength(50);

                    b.Property<int>("salutation");

                    b.Property<string>("workEmail")
                        .HasMaxLength(50);

                    b.HasKey("customerLineId");

                    b.HasIndex("customerId");

                    b.ToTable("CustomerLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Product", b =>
                {
                    b.Property<string>("productId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("barcode")
                        .HasMaxLength(50);

                    b.Property<string>("brandCode")
                        .HasMaxLength(20);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("familyCode")
                        .HasMaxLength(20);

                    b.Property<string>("productCode")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("productName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("productType");

                    b.Property<string>("serialNumber")
                        .HasMaxLength(50);

                    b.Property<int>("subFamilyCode");

                    b.Property<int>("uom");

                    b.HasKey("productId");

                    b.HasIndex("brandCode");

                    b.HasIndex("familyCode");

                    b.ToTable("Product");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.PurchaseOrder", b =>
                {
                    b.Property<string>("purchaseOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("deliveryAddress")
                        .HasMaxLength(50);

                    b.Property<DateTime>("deliveryDate");

                    b.Property<string>("description")
                        .HasMaxLength(100);

                    b.Property<string>("picInternal")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("picVendor")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<DateTime>("poDate");

                    b.Property<string>("purchaseOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("purchaseOrderStatus");

                    b.Property<string>("purchaseReceiveNumber");

                    b.Property<string>("referenceNumberExternal")
                        .HasMaxLength(30);

                    b.Property<string>("referenceNumberInternal")
                        .HasMaxLength(30);

                    b.Property<int>("top");

                    b.Property<decimal>("totalDiscountAmount");

                    b.Property<decimal>("totalOrderAmount");

                    b.Property<string>("vendorId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.HasKey("purchaseOrderId");

                    b.HasIndex("branchId");

                    b.HasIndex("vendorId");

                    b.ToTable("PurchaseOrder");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.PurchaseOrderLine", b =>
                {
                    b.Property<string>("purchaseOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<decimal>("discountAmount");

                    b.Property<decimal>("price");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<string>("purchaseOrderId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<decimal>("totalAmount");

                    b.HasKey("purchaseOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("purchaseOrderId");

                    b.ToTable("PurchaseOrderLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Receiving", b =>
                {
                    b.Property<string>("receivingId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("purchaseOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("receivingDate");

                    b.Property<string>("receivingNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("vendorDO")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("vendorId")
                        .HasMaxLength(38);

                    b.Property<string>("vendorInvoice")
                        .HasMaxLength(50);

                    b.Property<string>("warehouseId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.HasKey("receivingId");

                    b.HasIndex("branchId");

                    b.HasIndex("purchaseOrderId");

                    b.HasIndex("vendorId");

                    b.HasIndex("warehouseId");

                    b.ToTable("Receiving");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.ReceivingLine", b =>
                {
                    b.Property<string>("receivingLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<float>("qtyReceive");

                    b.Property<string>("receivingId")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseId")
                        .HasMaxLength(38);

                    b.HasKey("receivingLineId");

                    b.HasIndex("branchId");

                    b.HasIndex("productId");

                    b.HasIndex("receivingId");

                    b.HasIndex("warehouseId");

                    b.ToTable("ReceivingLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.SalesOrder", b =>
                {
                    b.Property<string>("salesOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<string>("deliveryAddress")
                        .HasMaxLength(50);

                    b.Property<DateTime>("deliveryDate");

                    b.Property<string>("description")
                        .HasMaxLength(100);

                    b.Property<string>("picCustomer")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("picInternal")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.Property<string>("referenceNumberExternal")
                        .HasMaxLength(30);

                    b.Property<string>("referenceNumberInternal")
                        .HasMaxLength(30);

                    b.Property<string>("salesOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("salesOrderStatus");

                    b.Property<string>("salesShipmentNumber");

                    b.Property<DateTime>("soDate");

                    b.Property<int>("top");

                    b.Property<decimal>("totalDiscountAmount");

                    b.Property<decimal>("totalOrderAmount");

                    b.HasKey("salesOrderId");

                    b.HasIndex("branchId");

                    b.HasIndex("customerId");

                    b.ToTable("SalesOrder");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.SalesOrderLine", b =>
                {
                    b.Property<string>("salesOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<decimal>("discountAmount");

                    b.Property<decimal>("price");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<string>("salesOrderId")
                        .HasMaxLength(38);

                    b.Property<decimal>("totalAmount");

                    b.HasKey("salesOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("salesOrderId");

                    b.ToTable("SalesOrderLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Shipment", b =>
                {
                    b.Property<string>("shipmentId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("customerId")
                        .HasMaxLength(38);

                    b.Property<string>("customerPO")
                        .HasMaxLength(50);

                    b.Property<int>("expeditionMode");

                    b.Property<int>("expeditionType");

                    b.Property<string>("invoice")
                        .HasMaxLength(50);

                    b.Property<string>("salesOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("shipmentDate");

                    b.Property<string>("shipmentNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("warehouseId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.HasKey("shipmentId");

                    b.HasIndex("branchId");

                    b.HasIndex("customerId");

                    b.HasIndex("salesOrderId");

                    b.HasIndex("warehouseId");

                    b.ToTable("Shipment");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.ShipmentLine", b =>
                {
                    b.Property<string>("shipmentLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<float>("qtyShipment");

                    b.Property<string>("shipmentId")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseId")
                        .HasMaxLength(38);

                    b.HasKey("shipmentLineId");

                    b.HasIndex("branchId");

                    b.HasIndex("productId");

                    b.HasIndex("shipmentId");

                    b.HasIndex("warehouseId");

                    b.ToTable("ShipmentLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferIn", b =>
                {
                    b.Property<string>("transferInId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchFrombranchId");

                    b.Property<string>("branchIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("branchIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("branchTobranchId");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<DateTime>("transferInDate");

                    b.Property<string>("transferInNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("transferOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<string>("warehouseFromwarehouseId");

                    b.Property<string>("warehouseIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseTowarehouseId");

                    b.HasKey("transferInId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("transferOrderId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferIn");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferInLine", b =>
                {
                    b.Property<string>("transferInLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<string>("transferInId")
                        .HasMaxLength(38);

                    b.HasKey("transferInLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferInId");

                    b.ToTable("TransferInLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferOrder", b =>
                {
                    b.Property<string>("transferOrderId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchFrombranchId");

                    b.Property<string>("branchIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("branchIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("branchTobranchId");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<bool>("isIssued");

                    b.Property<bool>("isReceived");

                    b.Property<string>("picName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("transferOrderDate");

                    b.Property<string>("transferOrderNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("transferOrderStatus");

                    b.Property<string>("warehouseFromwarehouseId");

                    b.Property<string>("warehouseIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseTowarehouseId");

                    b.HasKey("transferOrderId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferOrder");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferOrderLine", b =>
                {
                    b.Property<string>("transferOrderLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<string>("transferOrderId")
                        .HasMaxLength(38);

                    b.HasKey("transferOrderLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferOrderId");

                    b.ToTable("TransferOrderLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferOut", b =>
                {
                    b.Property<string>("transferOutId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("branchFrombranchId");

                    b.Property<string>("branchIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("branchIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("branchTobranchId");

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<string>("transferOrderId")
                        .IsRequired()
                        .HasMaxLength(38);

                    b.Property<DateTime>("transferOutDate");

                    b.Property<string>("transferOutNumber")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("warehouseFromwarehouseId");

                    b.Property<string>("warehouseIdFrom")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseIdTo")
                        .HasMaxLength(38);

                    b.Property<string>("warehouseTowarehouseId");

                    b.HasKey("transferOutId");

                    b.HasIndex("branchFrombranchId");

                    b.HasIndex("branchTobranchId");

                    b.HasIndex("transferOrderId");

                    b.HasIndex("warehouseFromwarehouseId");

                    b.HasIndex("warehouseTowarehouseId");

                    b.ToTable("TransferOut");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferOutLine", b =>
                {
                    b.Property<string>("transferOutLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("productId")
                        .HasMaxLength(38);

                    b.Property<float>("qty");

                    b.Property<float>("qtyInventory");

                    b.Property<string>("transferOutId")
                        .HasMaxLength(38);

                    b.HasKey("transferOutLineId");

                    b.HasIndex("productId");

                    b.HasIndex("transferOutId");

                    b.ToTable("TransferOutLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Vendor", b =>
                {
                    b.Property<string>("vendorId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("HasChild");

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<int>("size");

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.Property<string>("vendorName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("vendorId");

                    b.ToTable("Vendor");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.VendorLine", b =>
                {
                    b.Property<string>("vendorLineId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("fax")
                        .HasMaxLength(20);

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<int>("gender");

                    b.Property<string>("jobTitle")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(20);

                    b.Property<string>("middleName")
                        .HasMaxLength(20);

                    b.Property<string>("mobilePhone")
                        .HasMaxLength(20);

                    b.Property<string>("nickName")
                        .HasMaxLength(20);

                    b.Property<string>("officePhone")
                        .HasMaxLength(20);

                    b.Property<string>("personalEmail")
                        .HasMaxLength(50);

                    b.Property<int>("salutation");

                    b.Property<string>("vendorId")
                        .HasMaxLength(38);

                    b.Property<string>("workEmail")
                        .HasMaxLength(50);

                    b.HasKey("vendorLineId");

                    b.HasIndex("vendorId");

                    b.ToTable("VendorLine");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Warehouse", b =>
                {
                    b.Property<string>("warehouseId")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(38);

                    b.Property<string>("branchId")
                        .HasMaxLength(38);

                    b.Property<string>("city")
                        .HasMaxLength(30);

                    b.Property<string>("country")
                        .HasMaxLength(30);

                    b.Property<DateTime>("createdAt");

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("province")
                        .HasMaxLength(30);

                    b.Property<string>("street1")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("street2")
                        .HasMaxLength(50);

                    b.Property<string>("warehouseName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("warehouseId");

                    b.HasIndex("branchId");

                    b.ToTable("Warehouse");
                });

            modelBuilder.Entity("AgnusCrm.Models.Item", b =>
                {
                    b.Property<string>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("price");

                    b.Property<string>("productCode");

                    b.Property<string>("productId");

                    b.Property<int>("quantity");

                    b.HasKey("id");

                    b.HasIndex("productId");

                    b.ToTable("Item");
                });

            modelBuilder.Entity("AgnusCrm.Models.PriceList.ViewPriceList", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("brand_desc");

                    b.Property<string>("desc");

                    b.Property<bool>("encomenda");

                    b.Property<string>("family_desc");

                    b.Property<double>("price");

                    b.Property<double>("stock");

                    b.Property<string>("subFamily_desc");

                    b.HasKey("id");

                    b.ToTable("ViewPriceList");
                });

            modelBuilder.Entity("AgnusCrm.Models.ProductPrice", b =>
                {
                    b.Property<string>("productCode");

                    b.Property<string>("coin")
                        .HasMaxLength(3);

                    b.Property<string>("unity")
                        .HasMaxLength(5);

                    b.Property<double>("pvp1");

                    b.Property<bool>("pvp1VatInclude");

                    b.Property<double>("pvp2");

                    b.Property<bool>("pvp2VatInclude");

                    b.Property<double>("pvp3");

                    b.Property<bool>("pvp3VatInclude");

                    b.Property<double>("pvp4");

                    b.Property<bool>("pvp4VatInclude");

                    b.Property<double>("pvp5");

                    b.Property<bool>("pvp5VatInclude");

                    b.Property<double>("pvp6");

                    b.Property<bool>("pvp6VatInclude");

                    b.HasKey("productCode", "coin", "unity");

                    b.HasIndex("coin");

                    b.HasIndex("unity");

                    b.ToTable("ProductPrice");
                });

            modelBuilder.Entity("AgnusCrm.Models.SubFamily", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("code")
                        .HasMaxLength(20);

                    b.Property<string>("description")
                        .HasMaxLength(50);

                    b.Property<string>("familyCode")
                        .HasMaxLength(20);

                    b.HasKey("id");

                    b.HasIndex("familyCode");

                    b.ToTable("SubFamily");
                });

            modelBuilder.Entity("AgnusCrm.Models.Unity", b =>
                {
                    b.Property<string>("code")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(5);

                    b.Property<string>("desc")
                        .HasMaxLength(50);

                    b.Property<int>("round");

                    b.HasKey("code");

                    b.ToTable("Unity");

                    b.HasData(
                        new
                        {
                            code = "UN",
                            desc = "Unidades",
                            round = 2
                        });
                });

            modelBuilder.Entity("AgnusCrm.Models.View_PriceList", b =>
                {
                    b.Property<string>("artigo")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("artigo_Desc");

                    b.Property<string>("familia");

                    b.Property<string>("familia_Desc");

                    b.Property<string>("marca");

                    b.Property<string>("marca_Desc");

                    b.Property<double>("preco");

                    b.Property<double>("stock");

                    b.Property<string>("subFamilia");

                    b.Property<string>("subFamilia_Desc");

                    b.HasKey("artigo");

                    b.ToTable("View_PriceList");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Name")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email")
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers");

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ClaimType");

                    b.Property<string>("ClaimValue");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<string>("ProviderDisplayName");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<string>("Value");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens");
                });

            modelBuilder.Entity("AgnusCrm.Models.ApplicationUser", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityUser");

                    b.Property<bool>("AccountExecutiveRole");

                    b.Property<bool>("ActivityRole");

                    b.Property<bool>("ApplicationUserRole");

                    b.Property<bool>("BranchRole");

                    b.Property<bool>("ChannelRole");

                    b.Property<bool>("CustomerLineRole");

                    b.Property<bool>("CustomerRole");

                    b.Property<bool>("DashboardRole");

                    b.Property<bool>("LeadLineRole");

                    b.Property<bool>("LeadRole");

                    b.Property<bool>("OpportunityLineRole");

                    b.Property<bool>("OpportunityRole");

                    b.Property<bool>("ProductRole");

                    b.Property<bool>("PurchaseOrderLineRole");

                    b.Property<bool>("PurchaseOrderRole");

                    b.Property<bool>("RatingRole");

                    b.Property<bool>("ReceivingLineRole");

                    b.Property<bool>("ReceivingRole");

                    b.Property<bool>("SalesOrderLineRole");

                    b.Property<bool>("SalesOrderRole");

                    b.Property<bool>("ShipmentLineRole");

                    b.Property<bool>("ShipmentRole");

                    b.Property<bool>("StageRole");

                    b.Property<bool>("StockRole");

                    b.Property<bool>("TransferInLineRole");

                    b.Property<bool>("TransferInRole");

                    b.Property<bool>("TransferOrderLineRole");

                    b.Property<bool>("TransferOrderRole");

                    b.Property<bool>("TransferOutLineRole");

                    b.Property<bool>("TransferOutRole");

                    b.Property<bool>("VendorLineRole");

                    b.Property<bool>("VendorRole");

                    b.Property<bool>("WarehouseRole");

                    b.Property<bool>("isSuperAdmin");

                    b.Property<string>("profilePictureUrl");

                    b.HasDiscriminator().HasValue("ApplicationUser");
                });

            modelBuilder.Entity("AgnusCrm.Models.Contact_Entity", b =>
                {
                    b.HasOne("AgnusCrm.Models.Contact", "contact")
                        .WithMany("contact_Itens")
                        .HasForeignKey("contactId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgnusCrm.Models.Entity", "entity")
                        .WithMany("listContact")
                        .HasForeignKey("entityId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.Lead", b =>
                {
                    b.HasOne("AgnusCrm.Models.Crm.AccountExecutive", "accountExecutive")
                        .WithMany()
                        .HasForeignKey("accountExecutiveId");

                    b.HasOne("AgnusCrm.Models.Crm.Channel", "channel")
                        .WithMany()
                        .HasForeignKey("channelId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.LeadLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Crm.Activity", "activity")
                        .WithMany()
                        .HasForeignKey("activityId");

                    b.HasOne("AgnusCrm.Models.Crm.Lead", "lead")
                        .WithMany("leadLine")
                        .HasForeignKey("leadId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.Opportunity", b =>
                {
                    b.HasOne("AgnusCrm.Models.Crm.AccountExecutive", "accountExecutive")
                        .WithMany()
                        .HasForeignKey("accountExecutiveId");

                    b.HasOne("AgnusCrm.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId");

                    b.HasOne("AgnusCrm.Models.Crm.Rating", "rating")
                        .WithMany()
                        .HasForeignKey("ratingId");

                    b.HasOne("AgnusCrm.Models.Crm.Stage", "stage")
                        .WithMany()
                        .HasForeignKey("stageId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Crm.OpportunityLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Crm.Activity", "activity")
                        .WithMany()
                        .HasForeignKey("activityId");

                    b.HasOne("AgnusCrm.Models.Crm.Opportunity", "opportunity")
                        .WithMany("opportunityLine")
                        .HasForeignKey("opportunityId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Entity", b =>
                {
                    b.HasOne("AgnusCrm.Models.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("coin");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.CustomerLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Customer", "customer")
                        .WithMany("customerLine")
                        .HasForeignKey("customerId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Product", b =>
                {
                    b.HasOne("AgnusCrm.Models.Brand")
                        .WithMany("listProducts")
                        .HasForeignKey("brandCode");

                    b.HasOne("AgnusCrm.Models.Family")
                        .WithMany("listProducts")
                        .HasForeignKey("familyCode");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.PurchaseOrder", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgnusCrm.Models.Invent.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.PurchaseOrderLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("AgnusCrm.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany("purchaseOrderLine")
                        .HasForeignKey("purchaseOrderId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Receiving", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("AgnusCrm.Models.Invent.PurchaseOrder", "purchaseOrder")
                        .WithMany()
                        .HasForeignKey("purchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgnusCrm.Models.Invent.Vendor", "vendor")
                        .WithMany()
                        .HasForeignKey("vendorId");

                    b.HasOne("AgnusCrm.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.ReceivingLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("AgnusCrm.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("AgnusCrm.Models.Invent.Receiving", "receiving")
                        .WithMany("receivingLine")
                        .HasForeignKey("receivingId");

                    b.HasOne("AgnusCrm.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.SalesOrder", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgnusCrm.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.SalesOrderLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("AgnusCrm.Models.Invent.SalesOrder", "salesOrder")
                        .WithMany("salesOrderLine")
                        .HasForeignKey("salesOrderId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Shipment", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("AgnusCrm.Models.Invent.Customer", "customer")
                        .WithMany()
                        .HasForeignKey("customerId");

                    b.HasOne("AgnusCrm.Models.Invent.SalesOrder", "salesOrder")
                        .WithMany()
                        .HasForeignKey("salesOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgnusCrm.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.ShipmentLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");

                    b.HasOne("AgnusCrm.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("AgnusCrm.Models.Invent.Shipment", "shipment")
                        .WithMany("shipmentLine")
                        .HasForeignKey("shipmentId");

                    b.HasOne("AgnusCrm.Models.Invent.Warehouse", "warehouse")
                        .WithMany()
                        .HasForeignKey("warehouseId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferIn", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("AgnusCrm.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany()
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgnusCrm.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("AgnusCrm.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferInLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("AgnusCrm.Models.Invent.TransferIn", "transferIn")
                        .WithMany("transferInLine")
                        .HasForeignKey("transferInId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferOrder", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("AgnusCrm.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("AgnusCrm.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferOrderLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("AgnusCrm.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany("transferOrderLine")
                        .HasForeignKey("transferOrderId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferOut", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branchFrom")
                        .WithMany()
                        .HasForeignKey("branchFrombranchId");

                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branchTo")
                        .WithMany()
                        .HasForeignKey("branchTobranchId");

                    b.HasOne("AgnusCrm.Models.Invent.TransferOrder", "transferOrder")
                        .WithMany()
                        .HasForeignKey("transferOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgnusCrm.Models.Invent.Warehouse", "warehouseFrom")
                        .WithMany()
                        .HasForeignKey("warehouseFromwarehouseId");

                    b.HasOne("AgnusCrm.Models.Invent.Warehouse", "warehouseTo")
                        .WithMany()
                        .HasForeignKey("warehouseTowarehouseId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.TransferOutLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Product", "product")
                        .WithMany()
                        .HasForeignKey("productId");

                    b.HasOne("AgnusCrm.Models.Invent.TransferOut", "transferOut")
                        .WithMany("transferOutLine")
                        .HasForeignKey("transferOutId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.VendorLine", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Vendor", "vendor")
                        .WithMany("vendorLine")
                        .HasForeignKey("vendorId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Invent.Warehouse", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Branch", "branch")
                        .WithMany()
                        .HasForeignKey("branchId");
                });

            modelBuilder.Entity("AgnusCrm.Models.Item", b =>
                {
                    b.HasOne("AgnusCrm.Models.Invent.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productId");
                });

            modelBuilder.Entity("AgnusCrm.Models.ProductPrice", b =>
                {
                    b.HasOne("AgnusCrm.Models.Coin", "Coin")
                        .WithMany()
                        .HasForeignKey("coin")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgnusCrm.Models.Invent.Product", "Product")
                        .WithMany()
                        .HasForeignKey("productCode")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("AgnusCrm.Models.Unity", "Unity")
                        .WithMany()
                        .HasForeignKey("unity")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("AgnusCrm.Models.SubFamily", b =>
                {
                    b.HasOne("AgnusCrm.Models.Family", "family")
                        .WithMany("listSubFamilys")
                        .HasForeignKey("familyCode");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
